.PHONY: clean All

All:
	@echo "----------Building project:[ final_sql - Debug ]----------"
	@cd "final_sql" && "$(MAKE)" -f  "final_sql.mk"
clean:
	@echo "----------Cleaning project:[ final_sql - Debug ]----------"
	@cd "final_sql" && "$(MAKE)" -f  "final_sql.mk" clean
